# Default values for crypto-visualizer-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: myacrregistrysk08.azurecr.io/streamlit-app1
  tag: latest
  pullPolicy: Always

imagePullSecrets: 
  - name: acr-secret
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8501

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


ingress:
  enabled: false

resources: {}