apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-visualizer-chart.fullname" . }}
  labels:
    {{- include "crypto-visualizer-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crypto-visualizer-chart.selectorLabels" . | nindent 4 }}


# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "crypto-visualizer-chart.fullname" . }}
#   labels:
#     {{- include "crypto-visualizer-chart.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "crypto-visualizer-chart.selectorLabels" . | nindent 4 }}
